### ISSUE TITLE
Visualisation & UI

### ISSUE THREAD

**Issue by Tobikay1896** [ereichl42/ODA-Pisa#8]
implementing a user interface (UI) to allow users to select specific columns of data from a dataset and visualize the correlation matrix heatmap based on the selected columns. The UI will enhance user interaction and facilitate the exploration of correlations within the dataset.

**Comment by ereichl42** [comment]
[] create user stories

**Comment by Tobikay1896** [comment]
Visualization and UI components have been developed, integrated and tested
